name: Build & Test

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  EMCC_VERSION: "6.0.0"
  EMCC_FASTCOMP_VERSION: "1.40.1-fastcomp"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd ./emsdk
          ./emsdk install ${{ env.EMCC_VERSION }}
          ./emsdk activate ${{ env.EMCC_VERSION }}
          ./upstream/emscripten/emcc -v

      - name: Install Emscripten Fastcomp
        run: |
          git clone https://github.com/emscripten-core/emsdk.git emsdk-fastcomp --branch 3.1.29
          cd ./emsdk-fastcomp
          ./emsdk install ${{ env.EMCC_FASTCOMP_VERSION }}
          ./emsdk activate ${{ env.EMCC_FASTCOMP_VERSION }}
          ./fastcomp/emscripten/emcc -v

      - name: npm Install
        run: npm install

      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile to Wasm & Test
        env:
          EMSDK_PATH: './emsdk'
          EMSDK_FASTCOMP_PATH: './emsdk-fastcomp'
        run: chomp test

      - name: Footprint
        env:
          EMSDK_PATH: './emsdk'
          EMSDK_FASTCOMP_PATH: './emsdk-fastcomp'
        run: chomp footprint

      - name: Benchmark Wasm
        env:
          EMSDK_PATH: './emsdk'
          EMSDK_FASTCOMP_PATH: './emsdk-fastcomp'
        run: chomp bench
